<?php

use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\Html;
/**
 * @file
 * Contains commerce_ginger.module.
 */


use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_mail
 */
function commerce_ginger_mail($key, &$message, $params) {

  switch ($key) {
    case 'order_mail':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $renderer = \Drupal::service('renderer');
      $message['body'][] = $renderer->renderPlain($params['body']);
      break;
  }
}




